export interface Tool {
  id: string;
  icon: string;
  name: string;
  tagline: string;
  tags: string[];
  rating: number;
  stars: number;
  color: "purple" | "green" | "cyan" | "pink" | "orange" | "lime" | "teal" | "yellow" | "red";
  categories: string[];
  editorsPick?: boolean;
  pros: string[];
  cons: string[];
  price: string;
  link: string;
}

export const tools: Tool[] = [
  {
    id: "claude",
    icon: "🟠",
    name: "Claude",
    tagline: "by Anthropic · Claude 3.5 Sonnet · The deep thinker",
    tags: ["Writing", "Analysis", "Coding"],
    rating: 4.9,
    stars: 5,
    color: "purple",
    categories: ["writing", "research"],
    editorsPick: true,
    pros: ["Nuanced, thoughtful answers", "Handles long documents (200K context)", "Feels like talking to someone smart"],
    cons: ["No image generation", "Usage limits can be frustrating"],
    price: "Free / $20 Pro",
    link: "https://claude.ai",
  },
  {
    id: "chatgpt",
    icon: "🟢",
    name: "ChatGPT",
    tagline: "by OpenAI · GPT-4o · The do-everything model",
    tags: ["Writing", "Coding", "Voice + Images"],
    rating: 4.5,
    stars: 4.5,
    color: "green",
    categories: ["writing", "research", "coding"],
    pros: ["Native voice & image gen", "Huge plugin ecosystem", "Everyone knows how to use it"],
    cons: ["Answers optimized to sound good", "Can be verbose and hedge-y"],
    price: "Free / $20 Plus",
    link: "https://chat.openai.com",
  },
  {
    id: "gemini",
    icon: "🔵",
    name: "Gemini",
    tagline: "by Google · Gemini 1.5 Pro · The connected one",
    tags: ["Research", "Google Workspace"],
    rating: 4.2,
    stars: 4,
    color: "cyan",
    categories: ["research"],
    pros: ["Google Docs / Drive integration", "Real-time web access", "Free tier is generous"],
    cons: ["Writing feels a bit corporate", "Still catching up on reasoning"],
    price: "Free / $20 Advanced",
    link: "https://gemini.google.com",
  },
  {
    id: "perplexity",
    icon: "🔣",
    name: "Perplexity",
    tagline: "The internet with an opinion",
    tags: ["Research", "News", "Citations"],
    rating: 4.7,
    stars: 5,
    color: "pink",
    categories: ["research"],
    pros: ["Always up-to-date", "Cites its sources", "Great free tier"],
    cons: ["Not great for creative work", "Answers can be surface-level"],
    price: "Free / $20 Pro",
    link: "https://perplexity.ai",
  },
  {
    id: "deepseek",
    icon: "🔷",
    name: "DeepSeek",
    tagline: "by DeepSeek · R1 · The open-source disruptor",
    tags: ["Coding", "Reasoning", "Open Source"],
    rating: 4.6,
    stars: 4.5,
    color: "cyan",
    categories: ["coding", "research"],
    editorsPick: true,
    pros: ["Completely free", "Rivals GPT-4 on benchmarks", "Open weights - run it yourself"],
    cons: ["Chinese company (data concerns)", "Less polished UX", "Reasoning can be slow"],
    price: "Free",
    link: "https://chat.deepseek.com",
  },
  {
    id: "midjourney",
    icon: "🎨",
    name: "Midjourney",
    tagline: "The art school dropout",
    tags: ["Images", "Art", "Design"],
    rating: 4.8,
    stars: 5,
    color: "orange",
    categories: ["images"],
    pros: ["Stunning aesthetic quality", "Huge active community", "Consistent style control"],
    cons: ["No free tier", "Discord-only (though web is coming)"],
    price: "From $10/mo",
    link: "https://midjourney.com",
  },
  {
    id: "cursor",
    icon: "⚡",
    name: "Cursor",
    tagline: "The IDE from the future",
    tags: ["Coding", "IDE", "Developers"],
    rating: 4.9,
    stars: 5,
    color: "lime",
    categories: ["coding"],
    editorsPick: true,
    pros: ["Understands your whole codebase", "Genuinely replaces a junior dev", "Based on VS Code"],
    cons: ["Coders only", "Costs add up on heavy use"],
    price: "Free / $20 Pro",
    link: "https://cursor.sh",
  },
  {
    id: "github-copilot",
    icon: "🤖",
    name: "GitHub Copilot",
    tagline: "The coding co-pilot you've heard of",
    tags: ["Coding", "Autocomplete"],
    rating: 4.3,
    stars: 4,
    color: "teal",
    categories: ["coding"],
    pros: ["Seamless GitHub integration", "Works in any editor"],
    cons: ["Cursor has overtaken it", "Best features need Pro"],
    price: "Free / $10 Pro",
    link: "https://github.com/features/copilot",
  },
  {
    id: "grok",
    icon: "🦊",
    name: "Grok",
    tagline: "by xAI · The wildcard",
    tags: ["Real-time", "X / Twitter", "Humor"],
    rating: 3.8,
    stars: 4,
    color: "yellow",
    categories: ["research", "writing"],
    pros: ["Real-time X/Twitter data", "Refreshingly unfiltered"],
    cons: ["Inconsistent quality", "Requires X Premium"],
    price: "With X Premium",
    link: "https://x.ai",
  },
  {
    id: "llama",
    icon: "🦙",
    name: "Llama 3.1",
    tagline: "by Meta · The open-source giant",
    tags: ["Open Source", "Self-hosted", "Privacy"],
    rating: 4.4,
    stars: 4,
    color: "purple",
    categories: ["coding", "writing"],
    pros: ["Run locally, total privacy", "405B model rivals GPT-4", "Completely free"],
    cons: ["Need beefy hardware for big models", "No official chat UI"],
    price: "Free (self-host)",
    link: "https://llama.meta.com",
  },
  {
    id: "runway",
    icon: "🎬",
    name: "Runway",
    tagline: "Gen-3 Alpha · AI video that actually works",
    tags: ["Video", "Creative", "Motion"],
    rating: 4.5,
    stars: 4.5,
    color: "red",
    categories: ["images"],
    pros: ["Best-in-class video generation", "Text-to-video actually works", "Great for creatives"],
    cons: ["Expensive for heavy use", "10-second clips only"],
    price: "From $12/mo",
    link: "https://runwayml.com",
  },
  {
    id: "notion-ai",
    icon: "📝",
    name: "Notion AI",
    tagline: "AI that lives in your workspace",
    tags: ["Writing", "Productivity", "Notes"],
    rating: 4.1,
    stars: 4,
    color: "teal",
    categories: ["writing"],
    pros: ["Seamless Notion integration", "Good for summaries & drafts", "No context switching"],
    cons: ["Only useful if you use Notion", "Not as smart as Claude/GPT"],
    price: "$10/mo add-on",
    link: "https://notion.so/product/ai",
  },
];

export const comparisonData = [
  {
    icon: "🟠",
    name: "Claude",
    bestFor: "Writing, thinking, analysis",
    freeTier: true,
    webAccess: "Pro",
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🟢",
    name: "ChatGPT",
    bestFor: "General tasks, plugins",
    freeTier: true,
    webAccess: true,
    imageGen: true,
    pricing: "freemium",
  },
  {
    icon: "🔵",
    name: "Gemini",
    bestFor: "Google Workspace users",
    freeTier: true,
    webAccess: true,
    imageGen: true,
    pricing: "freemium",
  },
  {
    icon: "🔣",
    name: "Perplexity",
    bestFor: "Research with citations",
    freeTier: true,
    webAccess: true,
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🔷",
    name: "DeepSeek",
    bestFor: "Free GPT-4 alternative",
    freeTier: true,
    webAccess: true,
    imageGen: false,
    pricing: "free",
  },
  {
    icon: "🎨",
    name: "Midjourney",
    bestFor: "Stunning AI art",
    freeTier: false,
    webAccess: false,
    imageGen: "★★★",
    pricing: "paid",
  },
  {
    icon: "⚡",
    name: "Cursor",
    bestFor: "Coding & dev projects",
    freeTier: true,
    webAccess: false,
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🤖",
    name: "GitHub Copilot",
    bestFor: "In-editor code suggestions",
    freeTier: true,
    webAccess: false,
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🦊",
    name: "Grok",
    bestFor: "Real-time Twitter data",
    freeTier: false,
    webAccess: true,
    imageGen: true,
    pricing: "paid",
  },
  {
    icon: "🦙",
    name: "Llama 3.1",
    bestFor: "Self-hosted, privacy",
    freeTier: true,
    webAccess: false,
    imageGen: false,
    pricing: "free",
  },
  {
    icon: "🎬",
    name: "Runway",
    bestFor: "AI video generation",
    freeTier: false,
    webAccess: false,
    imageGen: "Video",
    pricing: "paid",
  },
  {
    icon: "📝",
    name: "Notion AI",
    bestFor: "Notion power users",
    freeTier: false,
    webAccess: false,
    imageGen: false,
    pricing: "paid",
  },
];
