export interface Tool {
  id: string;
  icon: string;
  name: string;
  tagline: string;
  tags: string[];
  rating: number;
  stars: number;
  color: "purple" | "green" | "cyan" | "pink" | "orange" | "lime" | "teal" | "yellow" | "red";
  categories: string[];
  editorsPick?: boolean;
  pros: string[];
  cons: string[];
  price: string;
  link: string;
  fullReview?: string;
}

export const tools: Tool[] = [
  {
    id: "claude",
    icon: "🟠",
    name: "Claude",
    tagline: "by Anthropic · Claude 4 Opus · The deep thinker",
    tags: ["Writing", "Analysis", "Coding"],
    rating: 4.9,
    stars: 5,
    color: "purple",
    categories: ["writing", "research"],
    editorsPick: true,
    pros: ["Extended thinking for complex problems", "Best writing quality, period", "Handles huge context (200K tokens)"],
    cons: ["No image generation", "Usage limits can be frustrating"],
    price: "Free / $20 Pro",
    link: "https://claude.ai",
  },
  {
    id: "chatgpt",
    icon: "🟢",
    name: "ChatGPT",
    tagline: "by OpenAI · GPT-5.5 · The do-everything model",
    tags: ["Writing", "Coding", "Voice + Images"],
    rating: 4.7,
    stars: 5,
    color: "green",
    categories: ["writing", "research", "coding"],
    editorsPick: true,
    pros: ["Native voice & image gen", "Huge plugin ecosystem", "GPT-5.5 is genuinely impressive"],
    cons: ["Can still be verbose", "Pro tier getting expensive"],
    price: "Free / $20 Plus / $200 Pro",
    link: "https://chat.openai.com",
  },
  {
    id: "gemini",
    icon: "🔵",
    name: "Gemini",
    tagline: "by Google · Gemini 3.1 Pro · Finally competitive",
    tags: ["Research", "Google Workspace", "Multimodal"],
    rating: 4.5,
    stars: 4.5,
    color: "cyan",
    categories: ["research"],
    pros: ["Gemini 3 is genuinely great", "Deep Google integration", "1M token context window"],
    cons: ["Playing catch-up on vibes", "Enterprise focus can feel corporate"],
    price: "Free / $20 Advanced",
    link: "https://gemini.google.com",
  },
  {
    id: "perplexity",
    icon: "🔣",
    name: "Perplexity",
    tagline: "The internet with an opinion",
    tags: ["Research", "News", "Citations"],
    rating: 4.7,
    stars: 5,
    color: "pink",
    categories: ["research"],
    pros: ["Always up-to-date", "Cites its sources", "Great free tier"],
    cons: ["Not great for creative work", "Answers can be surface-level"],
    price: "Free / $20 Pro",
    link: "https://perplexity.ai",
  },
  {
    id: "deepseek",
    icon: "🔷",
    name: "DeepSeek",
    tagline: "by DeepSeek · R1 · The open-source disruptor",
    tags: ["Coding", "Reasoning", "Open Source"],
    rating: 4.6,
    stars: 4.5,
    color: "cyan",
    categories: ["coding", "research"],
    editorsPick: true,
    pros: ["Completely free", "R1 rivals o1 on reasoning", "Open weights - run it yourself"],
    cons: ["Chinese company (data concerns)", "Can be slow on complex reasoning"],
    price: "Free",
    link: "https://chat.deepseek.com",
  },
  {
    id: "midjourney",
    icon: "🎨",
    name: "Midjourney",
    tagline: "v6.1 · Still the aesthetic king",
    tags: ["Images", "Art", "Design"],
    rating: 4.8,
    stars: 5,
    color: "orange",
    categories: ["images"],
    pros: ["Stunning aesthetic quality", "Huge active community", "v6 is a massive leap"],
    cons: ["No free tier", "Web app still maturing"],
    price: "From $10/mo",
    link: "https://midjourney.com",
  },
  {
    id: "cursor",
    icon: "⚡",
    name: "Cursor",
    tagline: "The IDE from the future",
    tags: ["Coding", "IDE", "Developers"],
    rating: 4.9,
    stars: 5,
    color: "lime",
    categories: ["coding"],
    editorsPick: true,
    pros: ["Understands your whole codebase", "Genuinely replaces a junior dev", "Composer mode is magic"],
    cons: ["Coders only", "Costs add up on heavy use"],
    price: "Free / $20 Pro",
    link: "https://cursor.sh",
  },
  {
    id: "github-copilot",
    icon: "🤖",
    name: "GitHub Copilot",
    tagline: "The coding co-pilot everyone knows",
    tags: ["Coding", "Autocomplete"],
    rating: 4.2,
    stars: 4,
    color: "teal",
    categories: ["coding"],
    pros: ["Seamless GitHub integration", "Works in any editor", "Copilot Workspace is promising"],
    cons: ["Cursor has overtaken it", "Best features need Pro"],
    price: "Free / $10 Pro",
    link: "https://github.com/features/copilot",
  },
  {
    id: "grok",
    icon: "🦊",
    name: "Grok",
    tagline: "by xAI · Grok 3 · The unfiltered one",
    tags: ["Real-time", "X / Twitter", "Reasoning"],
    rating: 4.3,
    stars: 4,
    color: "yellow",
    categories: ["research", "writing"],
    pros: ["Real-time X/Twitter data", "Strong reasoning with Grok 3", "100K H100 training muscle"],
    cons: ["Requires X Premium", "Quality still inconsistent"],
    price: "With X Premium",
    link: "https://x.ai",
  },
  {
    id: "llama",
    icon: "🦙",
    name: "Llama 3.1",
    tagline: "by Meta · The open-source giant",
    tags: ["Open Source", "Self-hosted", "Privacy"],
    rating: 4.4,
    stars: 4,
    color: "purple",
    categories: ["coding", "writing"],
    pros: ["Run locally, total privacy", "405B model rivals GPT-4", "Completely free"],
    cons: ["Need beefy hardware for big models", "No official chat UI"],
    price: "Free (self-host)",
    link: "https://llama.meta.com",
  },
  {
    id: "runway",
    icon: "🎬",
    name: "Runway",
    tagline: "Gen-3 Alpha · AI video that actually works",
    tags: ["Video", "Creative", "Motion"],
    rating: 4.5,
    stars: 4.5,
    color: "red",
    categories: ["images"],
    pros: ["Best-in-class video generation", "Text-to-video actually works", "Great for creatives"],
    cons: ["Expensive for heavy use", "10-second clips only"],
    price: "From $12/mo",
    link: "https://runwayml.com",
  },
  {
    id: "sora",
    icon: "🎥",
    name: "Sora",
    tagline: "by OpenAI · Cinematic AI video",
    tags: ["Video", "Creative", "Cinematic"],
    rating: 4.6,
    stars: 4.5,
    color: "green",
    categories: ["images"],
    editorsPick: true,
    pros: ["Stunning cinematic quality", "60-second videos", "Understands physics"],
    cons: ["Still limited access", "Can be slow to generate"],
    price: "ChatGPT Plus / Pro",
    link: "https://openai.com/sora",
  },
  {
    id: "notion-ai",
    icon: "📝",
    name: "Notion AI",
    tagline: "AI that lives in your workspace",
    tags: ["Writing", "Productivity", "Notes"],
    rating: 4.1,
    stars: 4,
    color: "teal",
    categories: ["writing"],
    pros: ["Seamless Notion integration", "Good for summaries & drafts", "No context switching"],
    cons: ["Only useful if you use Notion", "Not as smart as Claude/GPT"],
    price: "$10/mo add-on",
    link: "https://notion.so/product/ai",
  },
  {
    id: "openclaw",
    icon: "🦞",
    name: "OpenClaw",
    tagline: "Open-source · Your AI, your rules",
    tags: ["Self-hosted", "Open Source", "Privacy"],
    rating: 4.7,
    stars: 5,
    color: "red",
    categories: ["coding", "writing", "research"],
    editorsPick: true,
    pros: ["Use any LLM (Claude, GPT, Llama)", "Run locally with full privacy", "Agentic tools & file access"],
    cons: ["Requires some technical setup", "BYOK (bring your own API keys)"],
    price: "Free (open source)",
    link: "https://github.com/OpenClaw/OpenClaw",
    fullReview: `OpenClaw is fundamentally different from ChatGPT, Claude, and other hosted AI chats. Instead of being a product with its own model, it's an open-source framework that lets you build your own AI assistant using any model you want.

**What makes it different:**
- **Model agnostic**: Plug in Claude, GPT-4, Gemini, Llama, or any other model. Switch between them freely.
- **Runs anywhere**: Desktop app (Mac, Windows, Linux), self-hosted server, or even mobile.
- **True privacy**: When running locally with Llama, your data never leaves your machine.
- **Agentic by design**: Built for tool use - browse the web, read PDFs, access files, execute code.

**Who it's for:**
OpenClaw is ideal for power users who want control. Developers who want to customize their AI stack. Privacy-conscious users who don't want their data on corporate servers. Teams who want to run AI internally.

**Who should skip it:**
If you just want to chat with an AI without thinking about infrastructure, stick with ChatGPT or Claude. OpenClaw requires you to bring your own API keys or run local models.

**The bottom line:**
OpenClaw represents where AI assistants are heading - personal, customizable, and under your control. Microsoft is already copying this "playbook" for Copilot. If you're technical enough to set it up, it's the most flexible option available.`,
  },
];

export const comparisonData = [
  {
    icon: "🟠",
    name: "Claude",
    bestFor: "Writing, thinking, analysis",
    freeTier: true,
    webAccess: "Pro",
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🟢",
    name: "ChatGPT",
    bestFor: "General tasks, everything",
    freeTier: true,
    webAccess: true,
    imageGen: true,
    pricing: "freemium",
  },
  {
    icon: "🔵",
    name: "Gemini",
    bestFor: "Google Workspace users",
    freeTier: true,
    webAccess: true,
    imageGen: true,
    pricing: "freemium",
  },
  {
    icon: "🔣",
    name: "Perplexity",
    bestFor: "Research with citations",
    freeTier: true,
    webAccess: true,
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🔷",
    name: "DeepSeek",
    bestFor: "Free reasoning powerhouse",
    freeTier: true,
    webAccess: true,
    imageGen: false,
    pricing: "free",
  },
  {
    icon: "🎨",
    name: "Midjourney",
    bestFor: "Stunning AI art",
    freeTier: false,
    webAccess: false,
    imageGen: "★★★",
    pricing: "paid",
  },
  {
    icon: "⚡",
    name: "Cursor",
    bestFor: "Coding & dev projects",
    freeTier: true,
    webAccess: false,
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🤖",
    name: "GitHub Copilot",
    bestFor: "In-editor code suggestions",
    freeTier: true,
    webAccess: false,
    imageGen: false,
    pricing: "freemium",
  },
  {
    icon: "🦊",
    name: "Grok",
    bestFor: "Real-time Twitter/X data",
    freeTier: false,
    webAccess: true,
    imageGen: true,
    pricing: "paid",
  },
  {
    icon: "🦙",
    name: "Llama 3.1",
    bestFor: "Self-hosted, privacy",
    freeTier: true,
    webAccess: false,
    imageGen: false,
    pricing: "free",
  },
  {
    icon: "🎬",
    name: "Runway",
    bestFor: "AI video generation",
    freeTier: false,
    webAccess: false,
    imageGen: "Video",
    pricing: "paid",
  },
  {
    icon: "🎥",
    name: "Sora",
    bestFor: "Cinematic AI video",
    freeTier: false,
    webAccess: false,
    imageGen: "Video",
    pricing: "paid",
  },
  {
    icon: "📝",
    name: "Notion AI",
    bestFor: "Notion power users",
    freeTier: false,
    webAccess: false,
    imageGen: false,
    pricing: "paid",
  },
  {
    icon: "🦞",
    name: "OpenClaw",
    bestFor: "Power users who want control",
    freeTier: true,
    webAccess: true,
    imageGen: "Via plugins",
    pricing: "free",
  },
];
